"""added Games table

Revision ID: 55a16d91ac19
Revises: 
Create Date: 2023-04-14 11:23:16.636684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a16d91ac19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('game_1', sa.Integer(), nullable=True),
    sa.Column('game_2', sa.Integer(), nullable=True),
    sa.Column('game_3', sa.Integer(), nullable=True),
    sa.Column('avg_game', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
